onlyBuiltDependencies:
  - '@swc/core'
  - canvas
  - pdfkit
  - '@tailwindcss/oxide'
  - esbuild
  - '@nestjs/core'
  - '@scarf/scarf'
  - argon2
  - msgpackr-extract
  - sharp

patchedDependencies:
  arctic: pnpm/patches/arctic.patch
