import type { ListInputSchema as ListInputSchemaBase } from '#lib/core/schema';
import type * as S from '#app/api/schema';
import type { Jsonify } from 'type-fest';

export type ConnectionAuthorizationOutputSchema = S.ConnectionAuthorizationOutputSchema;
export type WorkflowListOutputSchema = Jsonify<S.WorkflowListOutputSchema>;
export type ConnectionWithProviderSchema = S.ConnectionWithProviderSchema;
export type FolderListOutputSchema = Jsonify<S.FolderListOutputSchema>;
export type ConnectionTestOutputSchema = S.ConnectionTestOutputSchema;
export type WorkflowUpdateInputSchema = S.WorkflowUpdateInputSchema;
export type WorkflowDetailSchema = Jsonify<S.WorkflowDetailSchema>;
export type ProviderListOutputSchema = S.ProviderListOutputSchema;
export type ActivityListOutputSchema = S.ActivityListOutputSchema;
export type WorkflowBasicSchema = Jsonify<S.WorkflowBasicSchema>;
export type LoginOutputSchema = Jsonify<S.LoginOutputSchema>;
export type DashboardOutputSchema = S.DashboardOutputSchema;
export type UserListOutputSchema = S.UserListOutputSchema;
export type ActivitySchema = Jsonify<S.ActivitySchema>;
export type WorkflowSchema = Jsonify<S.WorkflowSchema>;
export type FolderSchema = Jsonify<S.FolderSchema>;
export type ListInputSchema = ListInputSchemaBase;
export type ProviderSchema = S.ProviderSchema;
export type UserSchema = Jsonify<S.UserSchema>;
