import { ApiProperty } from '@nestjs/swagger';
import { Workflow } from '@prisma/client';

export class WorkflowBasicSchema implements Workflow {
  @ApiProperty({
    description:
      'A unique numeric identifier for the workflow, generated by the database.',
    example: 101,
  })
  id: number;

  @ApiProperty({
    description:
      'A unique string key used to reference the workflow programmatically.',
    example: 'SyncOrdersShopify',
  })
  key: string;

  @ApiProperty({
    description: 'The human-readable name of the workflow.',
    example: 'Sync Orders from Shopify',
  })
  name: string;

  @ApiProperty({
    description:
      'The ID of the folder that contains this workflow. Null if not assigned to any folder.',
    required: false,
    example: 12,
  })
  folderId: number | null;

  @ApiProperty({
    description: 'Indicates whether the workflow is currently active.',
    example: true,
  })
  active: boolean;

  @ApiProperty({
    description: 'The date and time when the workflow was created.',
    format: 'date-time',
    example: '2023-10-01T12:00:00Z',
  })
  createdAt: Date;

  @ApiProperty({
    description:
      'The date and time when the workflow was last updated. May be null if never updated.',
    format: 'date-time',
    example: '2023-10-02T15:30:00Z',
  })
  updatedAt: Date | null;
}
